### ISSUE TITLE
Delta-Diff-Compression?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [proepkes/UnityLockstep#33]

**Comment by proepkes** [comment]
Since only input is sent over the network, the bandwidth consumption should be relatively small in comparison to full state-synchronization. However, the input-data gets compressed using the default System.IO.Compression.DeflateStream

To rollback the simulation, the fulll gamestate is stored as Entities with the Backup-Component [see wiki](https://github.com/proepkes/UnityLockstep/wiki/Entity-Identifiers), no delta-diff there
